### ISSUE TITLE
how to get started

### ISSUE THREAD

**Issue by enthural** [dockpanelsuite/dockpanelsuite_docs#1]
In latest Visual Studio 2017, you don't need the following.
how do i use it on the visual sutdio 2017?

**Comment by lextm** [comment]
http://docs.dockpanelsuite.com/getting-started/installing-on-windows.html

**Comment by enthural** [comment]
thanks,i saw it,but it is not detail for a new starter.

**Comment by lextm** [comment]
You have to define how "new" you are as a starter.

All our articles assume the readers have basic understanding of .NET Framework and Windows Forms. If you don't know that, Microsoft has its own guides,

https://docs.microsoft.com/en-us/dotnet/framework/winforms/getting-started-with-windows-forms
